spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/channel_invite
    username: root
    password: root
  jpa:
    database: "postgresql"
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
kafka:
  host: localhost:9092