spring:
  cloud:
    gateway:
      globalCors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: '*'
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - OPTIONS
      routes:
        - id: user-not-auth
          uri: lb://user
          predicates:
            - Path=/users/signin, /users/signup
          filters:
            - RewritePath=/users(?<segment>/?.*), $\{segment}
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), $\{segment}
            - AuthFilter
        - id: channel
          uri: lb://channel
          predicates:
            - Path=/channel/**
          filters:
            - RewritePath=/channel(?<segment>/?.*), $\{segment}
            - AuthFilter
        - id: channel-invite-ASSISTANT_MANAGER
          uri: lb://channel-invite
          predicates:
            - Path=/channel-invite/channel/{channelId}/**
          filters:
            - RewritePath=/channel-invite(?<segment>/?.*), $\{segment}
            - AuthFilter
            - name: ChannelAuthFilter
              args:
                channelMemberRoles:
                  - MANAGER
                  - ASSISTANT_MANAGER
        - id: channel-invite-MEMBER
          uri: lb://channel-invite
          predicates:
            - Path=/channel-invite/channel/{channelId}/**
            - name: Method
              args:
                methods:
                  - GET
          filters:
            - RewritePath=/channel-invite(?<segment>/?.*), $\{segment}
            - AuthFilter
            - name: ChannelAuthFilter
              args:
                channelMemberRoles:
                  - MEMBER
        - id: chat-service-CHANNEL-MEMBER
          uri: lb://chat
          predicates:
            - Path=/chat/channel/{channelId}/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}
            - AuthFilter
            - name: ChannelAuthFilter
              args:
                channelMemberRoles:
                  - MEMBER
        - id: chat-service-ws
          uri: lb://chat
          predicates:
            - Path=/chat/ws/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}
        - id: channel-invite
          uri: lb://channel-invite
          predicates:
            - Path=/channel-invite/**
          filters:
            - RewritePath=/channel-invite(?<segment>/?.*), $\{segment}
            - AuthFilter
