spring:
  cloud:
    gateway:
      routes:
        - id: user-not-auth
          uri: lb://user
          predicates:
            - Path=/users/signin, /users/signup
          filters:
            - RewritePath=/users(?<segment>/?.*), $\{segment}
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), $\{segment}
            - AuthFilter
        - id: channel
          uri: lb://channel
          predicates:
            - Path=/channel/**
          filters:
            - RewritePath=/channel(?<segment>/?.*), $\{segment}
            - AuthFilter
        - id: channel-invite
          uri: lb://channel-invite
          predicates:
            - Path=/channel-invite/**
          filters:
            - RewritePath=/channel-invite(?<segment>/?.*), $\{segment}
            - AuthFilter
