server:
  port: 8085
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: channel-invite-orchestrator
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

